---
title: "Dashboard of NY_NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
data(ny_noaa)
df <- ny_noaa[sample(nrow(ny_noaa),10000),]%>% 
  separate(date,into = c("year","month","day")) %>% 
  janitor::clean_names() %>% 
  mutate(tmin=as.numeric(tmin)/10,
         tmax=as.numeric(tmax)/10) 

```

Column {data-width=650}
-----------------------------------------------------------------------

### The mean max temperature in January and July in each station across years

```{r}
label <- c('01'='January', '07'='July')
plot2 <- df %>% 
  filter(month=='01'|month=='07') %>%
  filter(!is.na(tmax)) %>% 
  group_by(month,year,id) %>% 
  summarise(month_mean=mean(tmax)) %>%
  ggplot(aes(x=factor(year),y=month_mean))+
    geom_boxplot()+
    facet_grid(.~month, labeller=as_labeller(label))+
  ggtitle('The mean max temperature in January and July in each station across years')+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplotly(plot2)

```

Column {data-width=350}
-----------------------------------------------------------------------

### tmax vs tmin for a sample size of 100,000

```{r}
plot1 <- ggplot(data=df, aes(x=tmax,y=tmin))+
  geom_hex()+
  ggtitle('tmax vs tmin for a sample size of 100,000')+
  theme(legend.position = "bottom")
ggplotly(plot1)
```

### The distribution of snowfall values between 0 and 100 by year

```{r}
plot3 <-df %>%
  filter(snow>0,snow<100) %>%
  ggplot(aes(x=snow, color=year))+
  geom_density( alpha=0.3)+
  ggtitle('The distribution of snowfall values between 0 and 100 by year')+
  theme(legend.position = "bottom")

ggplotly(plot3)
```

